services:
  flaskapp:
    build:
      dockerfile: ./publicapi/Dockerfile
    ports:
      - "5050:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - ENV=development
    depends_on:
      - db
    links:
      - db
  fastapiapp:
    build:
      dockerfile: ./resultsapi/Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    environment:
      - FASTAPI_ENV=development
      - FASTAPI_DEBUG=1
      - ENV=development
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./db:/var/lib/postgresql/data

